import type { Metadata } from "next";
import { Newsreader } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import {
  ClerkProvider,
} from '@clerk/nextjs'

const newsReader = Newsreader({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Saas App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={newsReader.className}
        >
          <Providers>
            {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
